
package de.neozo.jblockchain.node.dto;


public class AddressDTO {

    public byte[] getPrivateKey() {
		return privateKey;
	}

	public void setPrivateKey(byte[] privateKey) {
		this.privateKey = privateKey;
	}

	public void setHash(byte[] hash) {
		this.hash = hash;
	}

	/**
     * Unique identifier which can be generated by hashing name and publicKey
     */
    private byte[] hash;

    /**
     * Self-given name for this Address
     */
    private String name;

    /**
     * The public key for this Address to ensure everybody is able to verify signed messages
     */
    private byte[] publicKey;
    private byte[] privateKey;
    public AddressDTO() {
    }

    public AddressDTO(byte[] hash, String name, byte[] publicKey, byte[] privateKey) {
    	this.hash = hash;
    	this.name = name;
        this.publicKey = publicKey;
        this.privateKey = privateKey;
    }

    public byte[] getHash() {
        return hash;
    }



    public byte[] getPublicKey() {
        return publicKey;
    }

    public void setPublicKey(byte[] publicKey) {
        this.publicKey = publicKey;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

  


}